### ISSUE TITLE
이슈-테스트 - 체인지 타이틀 컬러 

### ISSUE THREAD

**Issue by genesis0714** [genesis0614/github-crash-course#1]
내 생각엔 주황색보단 녹색이 좋을것 같아염

```css
h1 {
  color: #00f245;
}
```
